### ISSUE TITLE
JS stubs for origin.js

### ISSUE THREAD

**Issue by matthewliu** [OriginProtocol/platform#1]
High-priority, as other features in this sprint are gated on this being done

**Comment by wanderingstan** [comment]
working in branch `issue/1_js_stubs`

**Comment by DanielVF** [comment]
I'm going to call this complete. We've got a new API style setup and issue #2 really covers implementing them.

**Comment by wanderingstan** [comment]
Hey Daniel, have you pushed the design for the new API? I'm set to talk with @tyleryasaka on Friday at 1:30 MT about origin.js. Would be great if you could join!

**Comment by aiham** [comment]
@wanderingstan I believe its in his api spike branch https://github.com/OriginProtocol/platform/tree/feature/2018-03-28_api_spike Check `origin.js/src/resources/listing.js`
