### ISSUE TITLE
Escrow and timeout functionality in smart contracts

### ISSUE THREAD

**Issue by matthewliu** [OriginProtocol/platform#10]
- [x] Purchase timeout from Buyer Pending to Seller Pending
- [x] Listing timeout to closed

**Comment by wanderingstan** [comment]
Note: A prerequisite for this is to make a purchase contract to trace the state of the transaction. (Right now "purchases" are instantaneous.)

Will be working in branch `issue/10_escrow`

**Comment by wanderingstan** [comment]
Escrow is there in https://github.com/OriginProtocol/platform/commit/8d21db289388d3dd155e007152cb9cc058bb06ca

Timeouts not yet. @Gzing may investigate this. 

Note that the `Purchase` contract is not yet used by `Listing` contract.

**Comment by DanielVF** [comment]
For testing the timeouts, truffle supports time manipulation. Yay!

https://ethereum.stackexchange.com/questions/21509/truffle-testrpc-time-manipulation

**Comment by DanielVF** [comment]
I'll implement the timeout functionality in the `Purchase` contract.

@matthewliu For our current simple default, how long should the timeout period be between when a listing is purchased and when a seller gets their money if the buyer does nothing?

**Comment by DanielVF** [comment]
I've coded the `Purchase` BUYER_PENDING timeout. I set it to 21 days for now, and we can easily change when we have an official number.

**Comment by DanielVF** [comment]
I've coded the Listing expiration. I set it to 60 days for now, and we can easily change that when we have an official number. @matthewliu
