### ISSUE TITLE
Estimate gas costs of creating listing and booking contracts

### ISSUE THREAD

**Issue by matthewliu** [OriginProtocol/platform#21]
Let's estimate how much it costs each time someone launches a new listing or booking. We expect this to go down over time, but for now, it is a big user experience impediment.

**Comment by DanielVF** [comment]
Our current cost to create a new listing, via spinning off a new listing contract is

- $0.89 if we want it done 95% in under 30 seconds
- $0.44 if between 5 to 15 minutes. 

This cost does go up as we add more code to the contract.
