### ISSUE TITLE
Update origin.js documentation

### ISSUE THREAD

**Issue by matthewliu** [OriginProtocol/platform#3]
Updates will need to be made on the docs repo, but want to track in this release.

https://github.com/OriginProtocol/docs

Changes reflected on docs.originprotocol.com

- [x] Fix really outdated stuff
- [x] Add instructions on workings on local docs
- [x] Add basic Listing api use with examples
- [ ] Explain how photos work
- [ ] Schema details
- [ ] IPFS Service

**Comment by wanderingstan** [comment]
This is for an old sprint (v0.2) so I'm going to close this out and create a updated issue around documentation for latest sprint.
