### ISSUE TITLE
Convert UserRegistry to use map instead of array

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/platform#39]
With a mapping we can look up a user by indexing off their wallet address. 

In current form, you'd have to walk the array to find a particular user. 

@tyleryasaka : any reason why this would be a bad idea?

**Comment by tyleryasaka** [comment]
@wanderingstan Sorry just saw this. Funny, when you posted this I had already created a PR which turns it into a map instead of an array 😄. You merged this recently so I think we can close this issue.

https://github.com/OriginProtocol/platform/blob/master/packages/contracts/contracts/UserRegistry.sol#L19

**Comment by wanderingstan** [comment]
@tyleryasaka My turn to be sorry. 

One thought: Do we need the `isSet` bool and related struct?, [here](https://github.com/OriginProtocol/platform/blob/master/packages/contracts/contracts/UserRegistry.sol#L25-L28)? I'm thinking we could just have a straight mapping and (I think) save the 256 bits needed for the bool:
```
    // Mapping of all users
    mapping(address => bytes32) public users;
``` 
In the mapping, if there is nothing at the address, it will return 0x00 indicating that we have nothing on that wallet address.

**Comment by tyleryasaka** [comment]
@wanderingstan You're right. [This answer](https://ethereum.stackexchange.com/questions/13021/how-can-you-figure-out-if-a-certain-key-exists-in-a-mapping-struct-defined-insi) is what made me think this was necessary, as I had run into this scenario on another contract before. Reading it now though, I see that just checking for the 0 value will be sufficient for us.

**Comment by wanderingstan** [comment]
Yeah, we have the advantage that the ipfs hash will never be zero. (Although that's an interesting question: I suppose its theoretically possible (lie a 1-in-a-zillion chance) that a document would hash to 0x00000000000000000000000000000000, but that's a risk we can afford!

**Comment by wanderingstan** [comment]
This is fixed as part of big pull https://github.com/OriginProtocol/platform/pull/44/

Will close when that gets merged.

**Comment by tyleryasaka** [comment]
Closing as all the issues discussed here have been resolved.
