### ISSUE TITLE
Create network utility functions in origin.js

### ISSUE THREAD

**Issue by matthewliu** [OriginProtocol/platform#57]
Network utility to post/fetch from smart contract & IPFS
- Always add/verify signature
- Every IPFS blob must be signed with private ETH key
- Optionally, do this as an extension of web3

**Comment by tyleryasaka** [comment]
@joshfraser @matthewliu Just discussed this with @wanderingstan and @DanielVF and we are not exactly sure what the objective is here. We already have a service that allows us to fetch and post data to IPFS. As far as signing, we're not sure what what value would be added by signing the IPFS data. It wouldn't add any security that is not already provided by the contracts themselves. Also, signing a message triggers a metamask UI popup that would be an extra step for the user.

**Comment by joshfraser** [comment]
Would be nice to be confident of the author of the content on IPFS & be able to verify those blobs independent of a smart contract.

But agree it's not required or worth the UX hit with the extra Metamask step.

Closing this out.
