### ISSUE TITLE
Deploy latest contracts to Rinkeby

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/platform#60]

**Comment by wanderingstan** [comment]
Depends on https://github.com/OriginProtocol/platform/issues/37

**Comment by DanielVF** [comment]
Merge tomorrow sounds good!

Version number is fine with me.

**Comment by wanderingstan** [comment]
We got out version 0.2.60. 

From now on this will be standard part of each release, and we should create a new issue around contract publishing + npm for each release.
