### ISSUE TITLE
Update buyListing to new contract logic

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/platform#62]
We've updated the contracts so that you now call `buyListing()` on the `Listing` contract, and *not* on the `ListingsRegistry` contract. 

We're still doing it the old way here:Current code for buying a listing: https://github.com/OriginProtocol/platform/blob/develop/packages/origin.js/src/contract-service.js#L109-L126

**Comment by wanderingstan** [comment]
@DanielVF -- From discord I believe you've got this fixed in your spike branch. Let's close it out as soon as we merge to `develop`

**Comment by DanielVF** [comment]
This has been merged.
