### ISSUE TITLE
Smart contract architecture for listings

### ISSUE THREAD

**Issue by matthewliu** [OriginProtocol/platform#7]
Current thinking is a master listing registry, individual contracts for each listing, then child contracts for booking instances

**Comment by matthewliu** [comment]
Same here.

Saw that this is marked as Done in the project tracker but not Closed. Can someone update on status?

**Comment by tyleryasaka** [comment]
We currently have solidity contracts in place for `ListingRegistry`, `Listing`, and `Purchase`. @wanderingstan can probably give a more comprehensive update. But I'll mention there has been some discussion in this related issue (contract mutability vs. immutability):

https://github.com/OriginProtocol/platform/issues/19

**Comment by DanielVF** [comment]
I think we've got our Listing/Purchase contract architecture in place for now. We may modify some of the internals when we add edit functionality, but for now, we are good.
