### ISSUE TITLE
Deposit functionality in listing smart contracts

### ISSUE THREAD

**Issue by matthewliu** [OriginProtocol/platform#9]
In some cases the seller may require additional deposit over the face value of the transaction. For example vrbo rental of a mansion.

**Comment by wanderingstan** [comment]
I forget what this was. Is this same as escrow? Or was this the deposits that you get back when leaving a review?

**Comment by wanderingstan** [comment]
@DanielVF - I assume we're punting on this until we are explicitly coding for home-sharing (and related) listings?

**Comment by DanielVF** [comment]
Correct, not until we make the sharing sprint.

**Comment by wanderingstan** [comment]
Since this is not on the roadmap for at least next month or so, and would be part of a bigger project of supporting a new vertical, I'm going to close this out.
